Development
PAWECOGmbH/saaster pull request #319
Opened 2023-03-28 13:50 UTC by ptruessel

2023-03-28 14:08 UTC, rbuechler commented
When the "Combined" theme is chosen, the default logo will still be displayed.
![image](https://user-images.githubusercontent.com/97615157/228264422-a867dc05-269b-4ef3-8b72-7ffbdf312c8d.png)

2023-03-28 14:11 UTC, rbuechler commented
When the "Horizontal dark" theme is chosen, the logo gets inverted. @ptruessel  Do you think we should remove the inversion?
![image](https://user-images.githubusercontent.com/97615157/228265760-5b4c7d09-0931-43df-9ed4-1cca31ffbb25.png)

2023-03-28 14:13 UTC, rbuechler requested changes
See [comments](https://github.com/PAWECOGmbH/saaster/pull/319#issuecomment-1486965790)

2023-03-30 12:53 UTC, dwilli241 approved these changes

2023-03-30 12:53 UTC, merged