enhancment: add redirect to plans, fix: redirect on modules with prices
PAWECOGmbH/saaster pull request #596
Opened 2024-12-23 14:56 UTC by phBucher0

-add redirect field to plan detail
-fixed redirect on priced modules

2024-12-24 06:42 UTC, ptruessel commented on config/db/core/V6__update-plans.sql
> +-- Hinzufügen des Feldes strRedirect zur Tabelle plans
Please write comments only in english

2024-12-24 06:46 UTC, ptruessel requested changes
See comments

2024-12-30 16:10 UTC, ptruessel approved these changes

2024-12-30 16:10 UTC, merged

2024-12-30 16:11 UTC, phBucher0 commented
Sehr Geehrte Damen und Herren 

Ich bin bis am 06.01.2025 abwesend. 

Wenn Sie eine dringende Anfrage haben schreiben Sie bitte eine E-Mail an ***@***.***

Freundlicher Gruss 

Philipp Bucher

2024-12-30 16:12 UTC, ptruessel commented
Grüezi!

Vielen Dank für Ihre Nachricht. Ich befinde mich in den wohlverdienten Ferien und kann Ihr E-Mail leider nicht persönlich beantworten. Ab 6. Januar 2025 bin ich wieder wie gewohnt für Sie erreichbar. Dieses E-Mail wird nicht weitergeleitet. Bitte wenden Sie sich bei dringenden Fällen an ***@***.***

Besten Dank!

Mit freundichem Gruss

Patrick Trüssel 

PAWECO GmbH